participants/john12.md

add participant

---

participants/yitik-kawatra.md

add participant-Yitik Kawatra

---

participants/anujji1999.md

anujji1999

---

participants/sanjitcodes.md

add participant-sanjit

---

participants/tarster.md

Successfully completed task-2 --tarster
For #20

add participant-tarster

---

participants/sunitijain111.md

add participanrt -sunitijain111

---

participants/tichnas.md

add participant-Sanchit Arora

---

participants/SjSingh101.md

Simranjeet Singh

---

participants/mishra-shruti96.md

add participant-shruti

---

participants/raksha009.md

add participant-Raksha Jain

---

participants/jhanvi12.md

add participant jhanvi uday
For #20

Jhanvi working copy task2

---

participants/Akanksha1212.md

add participant-akanksha

---

participants/SimranKaur.md

add participant-SimranKaur

---

participants/saloniankita.md

Completed task-2--saloniankita
For #20

add participant-saloniankita

---

changes.txt
participants/aayushibansal2001.md

Aayushibansal2001 task2

---

participants/Yashasvi191.md

add participant-Yashasvi

---

participants/Tanisha07.md

add participant-Tanisha

---

participants/omkaragrawal.md

add participant - OMKAR AGRAWAL

---

participants/Prerna-Goel.md

add participant-Prerna

---

participants/legedith.md

Markdown styling Jatin/Legedith

---

participants/vkr-code.md

add participant-Vanshika

---

participants/mansi35.md

styling participant mansi35

---

participants/Prerna-Goel.md

Styling done-Prerna

---

participants/raksha009.md

Styling - Raksha

---

participants/yitik-kawatra.md

styling done yitik

---

participants/aayushibansal2001.md

markdown styling added
For #50

markdown added by aayushi

---

participants/Akanksha1212.md

Markdown styling Akanksha

---

participants/SjSingh101.md

SjSingh101

---

participants/tarster.md

Styling md tarster

---

participants/Yashasvi191.md

Edited Yashasvi191.md file

---

participants/omkaragrawal.md

TASK 3 omkaragrawal.md

---

participants/simran212530.md

Styling-simran

---

participants/jhanvi12.md

I have created the styling in md file
For #50

styling participant jhanvi

---

participants/anujji1999.md

Styling done

---

participants/saloniankita.md

Added intro for task-3
For #50 
Kindly review it and let me know if any other change is required.

Markdown task-3

---

participants/Tanisha07.md

styling-Tanisha

---

participants/priyanka2109.md

add participant priyanka

---

participants/blackcrabb.md

styling Niyati

---

public/style.css

Closes #94 
I've added the brightness increasing decreasing effect in the cards along with the previous card effect staying as it is. Thus, making the issue at hand more focused upon.

Changing Card Style

---

views/events.ejs

Closes #109 
Added links for Instagram, Linkedin and Github

Added social media links

---

views/events.ejs

closes #122  
So I had made the necessary changes:
1.) Now only Github Link is there.
2.) I had removed the broken link queryloader.css from the events.ejs file as the file is not present in the location.

Added GitHub link and removed a broken CSS link

---

participants/sunitijain111.md

styling - sunitijain111

---

participants/mishra-shruti96.md

Markdown Task-3 Done
